// {{name}} - Minimal MCP Workspace
// Generated by nvmcp CLI

/**
 * Main entry point for {{name}}
 * 
 * This is a minimal MCP workspace. Start building your MCP components here.
 */
export function main(): void {
  console.log('🚀 {{name}} is running!')
  console.log('📋 Minimal MCP workspace ready for development')
}

// Auto-run if this is the main module
if (import.meta.url === `file://${process.argv[1]}`) {
  main()
} 