// {{name}} - MCP Workspace
// Generated by nvmcp CLI

export * from './types/index.js'

/**
 * Main entry point for {{name}}
 * 
 * This is a basic MCP workspace created with nvmcp CLI.
 * Add your MCP server, client, tools, and resources here.
 */
export function main(): void {
  console.log('🚀 Welcome to {{name}}!')
  console.log('📋 This is your MCP workspace')
  console.log('🔧 Start building your MCP components!')
}

// Auto-run if this is the main module
if (import.meta.url === `file://${process.argv[1]}`) {
  main()
} 